# Generated by Django 5.1 on 2024-09-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationlog",
            name="survivor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_logs",
                to="survivors.survivor",
            ),
        ),
    ]
