# Generated by Django 5.1 on 2024-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
